### ISSUE TITLE
Amazon Linux 2022 release candidate 0 (2022.0.20220728.1) uses OpenSSL 3.0 by default

### ISSUE THREAD

**Issue by Darth-Bobo** [rabbitmq/erlang-rpm#105]
Amazon have changed the base OpenSSL package to v3 and now erlang will not install because of a dependency problem:

e.g.:
  - nothing provides libcrypto.so.1.1()(64bit) needed by erlang-25.0.3-1.el8.x86_64
  - nothing provides libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) needed by erlang-25.0.3-1.el8.x86_64
  - nothing provides libcrypto.so.1.1(OPENSSL_1_1_1)(64bit) needed by erlang-25.0.3-1.el8.x86_64

In theory this could be resolved by downgrading OpenSSL, but that feels like the wrong way to go.

**Comment by michaelklishin** [comment]
Erlang 25 may or may not be ready for OpenSSL 3.0, which is very new. Using OpenSSL 1.1 is perfectly fine, the vast majority of software in the world uses 1.1.x.

I don't think we have the capacity on this team to work on Amazon Linux-specific issues and OpenSSL 3.0 at least until RabbitMQ 3.11 ships this fall. 

This is open source software, so you are welcome to dive in and report how compatible Erlang's TLS implementation is with 3.0, and add a variation of the build for it. All images used to produce the RPM are available as part of this repository.

**Comment by lukebakken** [comment]
A [quick search](https://github.com/erlang/otp/search?q=openssl+3.0&type=issues) in the [Erlang/OTP](https://github.com/erlang/otp/search?q=openssl+3.0&type=issues) repository returns this discussion:

https://github.com/erlang/otp/issues/4577#issuecomment-945396214

You will have to compile Erlang 25 from source to use OpenSSL 3.0.

Downgrading to OpenSSL 1.1 is perfectly acceptable as well.

**Comment by michaelklishin** [comment]
Assuming that Erlang 25's OpenSSL 3.0 support is robust, we can produce a new package type, `al2022` or something, that would build the package on AL 2022. That should be enough. It feels weird to special case a single vendor-specific distribution but given the scale and reach of AWS, we may not have a lot of options.

**Comment by Darth-Bobo** [comment]
I found that I could install openssl1.1 from the Fedora dev repo (https://fedora.mirrorservice.org/fedora/linux/development/rawhide/Everything/x86_64/os) and that has allowed erlang and rabbit to install so I now have a test node up and running.

Meanwhile I've also raised this with the AL 2022 development project since the previews all included OpenSSL 1.1

**Comment by erlmachinedev** [comment]
I faced the same issue when tried [Amazon Linux 2022](https://aws.amazon.com/linux/amazon-linux-2022/?amazon-linux-whats-new.sort-by=item.additionalFields.postDateTime&amazon-linux-whats-new.sort-order=desc) and the solution is to get [el9](https://github.com/rabbitmq/erlang-rpm/releases/download/v25.1.1/erlang-25.1.1-1.el9.x86_64.rpm) instead of el8. 

After that I successfully installed the lates Erlang and RabbitMQ on a top of OpenSLL 3.0

**Comment by michaelklishin** [comment]
I will make sure the README does mention this difference.

Now that Erlang 25.1 has made OpenSSL 3 support "officially production ready" we may consider to move to use OpenSSL 3 in a CentOS Stream 9 builds.

**Comment by michaelklishin** [comment]
This is no longer relevant as of Erlang/OTP 25.3 and #119.
