### ISSUE TITLE
RFE: upload EL9 assets to yum/dnf repositories at Cloudsmith / PackageCloud

### ISSUE THREAD

**Issue by space88man** [rabbitmq/erlang-rpm#109]
The instructions for installation from yum/dnf repositories give empty repos for EL9. (EL8 is working of course).

The reason for having the repository populated (vs directly downloading the RPM from this site) is for RPM mock builds which can be configured with  3rd party repositories, but cannot install an RPM from a URL link.

**Comment by michaelklishin** [comment]
@acogoluegnes should we look into this soon?
