### ISSUE TITLE
 25.2 has no rpm's 

### ISSUE THREAD

**Issue by ruben-herold** [rabbitmq/erlang-rpm#112]
hi,

the release of version 25.2 has no rpm's as assets. 

![image](https://user-images.githubusercontent.com/1569572/222736127-fb34ba19-bf1a-4e5c-bb04-9b55e6183142.png)

**Comment by michaelklishin** [comment]
We are aware of this. Just use 25.1, as far as RabbitMQ is concerned, there are no differences.

**Comment by acogoluegnes** [comment]
We're working on our pipelines and funny enough the RPM files for 25.2 were pushed about an hour ago.

**Comment by michaelklishin** [comment]
So [now it does](https://github.com/rabbitmq/erlang-rpm/releases/tag/v25.2.1).
