### ISSUE TITLE
Erlang Does Not Build on ARM Based Amazon Linux 2

### ISSUE THREAD

**Issue by CSimpiFoN** [rabbitmq/erlang-rpm#113]
### Describe the bug

When I try to build on ARM based Amazon Linux 2, the following error is dropped:
<code>configure: error: in `/tmp/erlang-rpm-25.3/BUILD/otp-OTP-25.3/erts':
configure: error: --enable-systemd was given, but test for systemd failed
See `config.log' for more details
ERROR: /tmp/erlang-rpm-25.3/BUILD/otp-OTP-25.3/erts/configure failed!
./configure: line 370: kill: (-9719) - No such process
error: Bad exit status from /tmp/erlang-rpm-25.3/tmp/rpm-tmp.uzzGXg (%build)

RPM build errors:
    Bad exit status from /tmp/erlang-rpm-25.3/tmp/rpm-tmp.uzzGXg (%build)
make: *** [erlang] Error 1</code>

I cannot really find anything obvious in the config.log file

### Reproduction steps

1. Download https://github.com/rabbitmq/erlang-rpm/archive/refs/tags/v25.3.tar.gz
2. Untar the archive
3. Change the directory to the unarchived folder
4. make (as per the README)

### Expected behavior

To get Erlang built and ready to be used by RabbitMQ

### Additional context

Want to install and use RabbitMQ on ARM based Amazon Linux 2 server

**Comment by michaelklishin** [comment]
Amazon Linux 2 is based on CentOS 7, an operating system this RPM and RabbitMQ no longer supports.

Amazon Linux 2023 is Fedora-based. Binary builds of this RPM certainly run just fine on it.

The oldest Erlang/OTP release that was compatible with CentOS 7 and OpenSSL 1.0 was [23.3.4.11](https://github.com/rabbitmq/erlang-rpm/releases/tag/v23.3.4.11).

**Comment by CSimpiFoN** [comment]
It fails on Amazon Linux 3 too:

<code>checking for systemd/sd-daemon.h... no
configure: error: in `/tmp/erlang-rpm-25.3/BUILD/otp-OTP-25.3/erts':
configure: error: --enable-systemd was given, but test for systemd failed
See `config.log' for more details
ERROR: /tmp/erlang-rpm-25.3/BUILD/otp-OTP-25.3/erts/configure failed!
./configure: line 370: kill: (-39330) - No such process
D:      waitpid(39138) rc 39138 status 100
D: /bin/sh failed: 100
error: Bad exit status from /tmp/erlang-rpm-25.3/tmp/rpm-tmp.RtzobR (%build)


RPM build errors:
    line 54: It's not recommended to have unversioned Obsoletes: Obsoletes: erlang-docbuilder
    Bad exit status from /tmp/erlang-rpm-25.3/tmp/rpm-tmp.RtzobR (%build)
ufdio:       1 reads,    17654 total bytes in 0.000011 secs
ufdio:       1 reads,     5707 total bytes in 0.000003 secs
ufdio:       1 reads,    17654 total bytes in 0.000002 secs
make: *** [Makefile:51: erlang] Error 1</code>
