### ISSUE TITLE
Error while trying to install 19.1 on CentOS 7

### ISSUE THREAD

**Issue by Arun-Trichy** [rabbitmq/erlang-rpm#22]
25347 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: erlang-19.1-1.el7.centos.x86_64
error: Directory not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/crypto-*/
error: Directory not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/ssl-*/
error: File not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/ssl-*/ebin
error: File not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/ssl-*/src
Executing(%doc): /bin/sh -e /root/Desktop/erlang-rpm-master/tmp/rpm-tmp.0HmeOo
+ umask 022
+ cd /root/Desktop/erlang-rpm-master/BUILD
+ cd otp-OTP-19.1
+ DOCDIR=/root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/share/doc/erlang-19.1
+ export DOCDIR
+ /usr/bin/mkdir -p /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/share/doc/erlang-19.1
+ cp -pr Erlang_ASL2_LICENSE.txt /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/share/doc/erlang-19.1
+ exit 0

RPM build errors:
    bogus date in %changelog: Thu Oct 13 2015 Michael Klishin <michael@rabbitmq.com> - 18.1
    Directory not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/crypto-*/
    Directory not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/ssl-*/
    File not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/ssl-*/ebin
    File not found by glob: /root/Desktop/erlang-rpm-master/BUILDROOT/erlang-19.1-1.el7.centos.x86_64/usr/lib64/erlang/lib/ssl-*/src
make: *** [erlang] Error 1

**Comment by michaelklishin** [comment]
You're trying to use master with Erlang 19.1.0. Please stick to published releases.

**Comment by Gsantomaggio** [comment]
hi @Arun-Trichy,
[Here]( https://github.com/rabbitmq/erlang-rpm/releases/tag/v1.4.5) you can find the packages for the Erlang/OTP version `19.1`.

We just released it.

**Comment by zduymz** [comment]
@Arun-Trichy I got the same error like yours when build erlang on amazon linux.
I installed these libraries and problem was solved.
# yum install ncurses-devel openssl-devel

**Comment by hatdropper1977** [comment]
@zduymz  That fixed it, thanks!
