### ISSUE TITLE
Update for Erlang OTP / 20

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/erlang-rpm#52]
1 - Create the branch for `19.x` versions 
2 - Update the `rpm(s)` for Erlang OTP 20, when it will be ready ([currently is RC](https://github.com/erlang/otp/releases/tag/OTP-20.0-rc1) ).

**Comment by dumbbell** [comment]
It should be done as of commit 19d54165d834a0785ede882043d09ca72812e9c8.

Builds are in progress.
