### ISSUE TITLE
Bintray repo has malformed URLs

### ISSUE THREAD

**Issue by jsumners** [rabbitmq/erlang-rpm#56]
Every link in https://dl.bintray.com/rabbitmq/erlang/ has a `:` prefixing the filename. For example, `https://dl.bintray.com/rabbitmq/erlang/repodata/:repomd.xml`. Browsing with Chrome, this doesn't cause an issue. But with other tools it generates a 404.

**Comment by michaelklishin** [comment]
https://bintray.com/rabbitmq/erlang is deprecated. Use https://bintray.com/rabbitmq/rpm/erlang. I don't see any [colons in URLs there](https://dl.bintray.com/rabbitmq/rpm/erlang/20/el/7/x86_64/).

**Comment by michaelklishin** [comment]
[Release artifacts](https://github.com/rabbitmq/erlang-rpm#release-artifacts) in our README use `bintray.com/rabbitmq/rpm/erlang`.

Yes, we have a few old Bintray repos at the moment that can cause confusion. They will be removed eventually as all GA release artifacts are switched to the "new" repos.
