### ISSUE TITLE
Cloudflare blocking rabbitmq-release-signing-key.asc from DigitalOcean

### ISSUE THREAD

**Issue by tonyarkles** [rabbitmq/erlang-rpm#57]
When I try to access `https://www.rabbitmq.com/rabbitmq-release-signing-key.asc` from a newly-provisioned DigitalOcean VM, Cloudflare appears to be serving a CAPTCHA to Yum/Curl instead of giving out the signing key.

Not sure if this is the right place to post this either. If it's not, please point me in the right direction.

**Comment by michaelklishin** [comment]
Not sure what led you to believe this repository has anything to do with the site.

Anyhow, that's one of the reasons why [the key is available from Bintray as well](http://www.rabbitmq.com/signatures.html). I will add an exception for the path on Cloud Flare at a later point.

**Comment by tonyarkles** [comment]
@michaelklishin the very first `yum.repos.d` file recommended in your `README.md` points at that file...

**Comment by michaelklishin** [comment]
@tonyarkles and FWIW it works for most people. We cannot control how/when Cloud Flare does its bot detection magic. Feel free to submit a PR for this README, which was in place before Cloud Flare was adopted.

**Comment by michaelklishin** [comment]
Cloud Flare already has browser integrity check disabled for the key. I cannot immediately think of what else we can do.

**Comment by michaelklishin** [comment]
Our docs now recommend Bintray over rabbitmq.com downloads in most visible places. We will probably distribute the key together with release artifacts on GitHub as well since we cannot consider Cloud Flare to be reliable for automation tools (at least at the moment) and we want to have a backup option to Bintray that can be used with `curl`, `wget` and similar (so, not a key server).

**Comment by tonyarkles** [comment]
Thanks! It definitely tripped me up today when the automation stuff I have set up started randomly failing. 

Thanks for all the hard work. We really love how straightforward and reliable RabbitMQ has been for us.
