### ISSUE TITLE
Docker Image Creation Fail

### ISSUE THREAD

**Issue by raushan2003** [rabbitmq/erlang-rpm#59]
Hi,

On using the Docker method for installation, the image creation is giving the following dependency error:

----------
Processing Conflict: libselinux-2.5-11.el7.x86_64 conflicts systemd < 219-20
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
Error: libselinux conflicts with fakesystemd-1-17.el7.centos.noarch
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
fakesystemd-1-17.el7.centos.noarch has installed conflicts systemd: fakesystemd-1-17.el7.centos.noarch
The command '/bin/sh -c yum -y update && yum clean all' returned a non-zero code: 1
----------

**Comment by michaelklishin** [comment]
> Error: libselinux conflicts with fakesystemd-1-17.el7.centos.noarch

I don't see how this has anything to do with package, it only has an implicit dependency on OpenSSL.

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users in the future.
