### ISSUE TITLE
There is no arm kernel installation package

### ISSUE THREAD

**Issue by Max-Qiu** [rabbitmq/erlang-rpm#84]
I will install RabbitMQ on the raspberrypi

**Comment by michaelklishin** [comment]
There are no plans to target ARM until there's enough interest.

Try Raspbian and the Debian package, which is [architecture-agnostic](https://github.com/rabbitmq/erlang-debian-package/blob/OTP-21.x/debian/stretch/debian/control#L19). There is no shortage of posts about [RabbitMQ on RaspberryPi](https://www.google.com/search?q=rabbitmq+on+raspberry+pi) and almost all that I've seen used Debian/Raspbian.
