### ISSUE TITLE
Erlang/OTP 22 cannot install rabbitmq-server-3.7.17-1.el7.noarch.rpm

### ISSUE THREAD

**Issue by wecloud2008** [rabbitmq/erlang-rpm#85]
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Eshell V10.4  (abort with ^G)
1> 

[root@li1861-201 opt]# rpm -ivh rabbitmq-server-3.7.17-1.el7.noarch.rpm 
warning: rabbitmq-server-3.7.17-1.el7.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 6026dfca: NOKEY
error: Failed dependencies:
	erlang >= 20.3 is needed by rabbitmq-server-3.7.17-1.el7.noarch

**Comment by wecloud2008** [comment]
[root@li1861-201 ~]# cd /opt
[root@li1861-201 opt]# ls
apache-maven-3.6.1             node-v10.16.3-linux-x64.tar.xz
apache-maven-3.6.1-bin.tar.gz  node-v10.16.3.tar.gz
apache-zookeeper-3.5.5.tar.gz  otp_src_22.0
erlang                         otp_src_22.0.tar.gz
kafka_2.12-2.3.0               rabbitmq-server-3.7.17-1.el7.noarch.rpm
kafka_2.12-2.3.0.tgz           redis-5.0.5
lnmp1.6                        redis-5.0.5.tar.gz
node-v10.16.3
[root@li1861-201 opt]# rpm -import https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
[root@li1861-201 opt]# rpm -ivh rabbitmq-server-3.7.17-1.el7.noarch.rpm 
error: Failed dependencies:
	erlang >= 20.3 is needed by rabbitmq-server-3.7.17-1.el7.noarch
[root@li1861-201 opt]#

**Comment by wecloud2008** [comment]
[root@li1861-201 opt]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@li1861-201 opt]#

**Comment by michaelklishin** [comment]
You must install a suitable Erlang package before RabbitMQ. See the [RPM installation guide](https://www.rabbitmq.com/install-rpm.html).
