### ISSUE TITLE
packagecloud (or other) repo

### ISSUE THREAD

**Issue by wyardley** [rabbitmq/erlang-rpm#9]
Would it be possible to push the latest RPMs to
https://packagecloud.io/rabbitmq/erlang
since RabbitMQ pushes their packages there? I'm guessing the EL6 one was mostly there to work around dependency issues, but it would be convenient to be able to access it as a yum repo.

**Comment by wyardley** [comment]
Woah, nevermind, I see that they showed up 3 hours ago, so guessing you saw my post elsewhere.

**Comment by wyardley** [comment]
ps - If it's possible to sign it, that would also be great.. not sure if that works with whatever processes are pushing it.

**Comment by michaelklishin** [comment]
@wyardley we will investigate signing, it should be quite straightforward.
