### ISSUE TITLE
error: Failed dependencies

### ISSUE THREAD

**Issue by hhhChan** [rabbitmq/erlang-rpm#94]
rpm -Uvh erlang-23.3.1-1.el7.x86_64.rpm 
warning: erlang-23.3.1-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 6026dfca: NOKEY
error: Failed dependencies:
	erlang(x86-64) = R16B-03.18.el7 is needed by (installed) erlang-examples-R16B-03.18.el7.x86_64

zero dependencies?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(

**Comment by michaelklishin** [comment]
I do not appreciate the sarcasm. This package has no dependencies other than an implicit one on modern OpenSSL.
You can [check it yourself](https://github.com/rabbitmq/erlang-rpm/blob/master/erlang.spec).

```
key ID 6026dfca: NOKEY
```

is the line you are looking for.

```
error: Failed dependencies:
erlang(x86-64) = R16B-03.18.el7 is needed by (installed) erlang-examples-R16B-03.18.el7.x86_64
```

has nothing to do with this pckage. Something named `erlang-examples-R16B-03.18.el7.x86_64` is missing a dependency
(and R16B03 is an Erlang version from many years ago).

So while you haven't provided any details as to what exactly has been done, my best guess
is that you did not [import the signing key](https://github.com/rabbitmq/erlang-rpm#signing-keys) and thus `yum` refused
to install this package. It would not satisfy the dependency below anyway, however, since you
try to install Erlang 23.3 and the "examples" one needs `R16B03`:

```
error: Failed dependencies:
erlang(x86-64) = R16B-03.18.el7 is needed by (installed) erlang-examples-R16B-03.18.el7.x86_64
```

**Comment by hhhChan** [comment]
> I do not appreciate the sarcasm. This package has no dependencies other than an implicit one on modern OpenSSL.
> You can [check it yourself](https://github.com/rabbitmq/erlang-rpm/blob/master/erlang.spec).
> 
> ```
> key ID 6026dfca: NOKEY
> ```
> 
> is the line you are looking for.
> 
> ```
> error: Failed dependencies:
> erlang(x86-64) = R16B-03.18.el7 is needed by (installed) erlang-examples-R16B-03.18.el7.x86_64
> ```
> 
> has nothing to do with this package. Something named `erlang-examples-R16B-03.18.el7.x86_64` is missing a dependency
> (and R16B03 is an Erlang version from many years ago).
> 
> So while you haven't provided any details as to what exactly has been done, my best guess
> is that you did not [import the signing key](https://github.com/rabbitmq/erlang-rpm#signing-keys) and thus `yum` refused
> to install this package. It would not satisfy the dependency below anyway, however, since you
> try to install Erlang 23.3 and the "examples" one needs `R16B03` which is **a version from 2014**:
> 
> ```
> error: Failed dependencies:
> erlang(x86-64) = R16B-03.18.el7 is needed by (installed) erlang-examples-R16B-03.18.el7.x86_64
> ```

I don't mean to be sarcastic，sorry
My commands ：
wget https://github.com/rabbitmq/erlang-rpm/releases/download/v23.3.1/erlang-23.31-1.el7.x86_64.rpm
->download has been done 
-> rpm -Uvh erlang-23.3.1-1.el7.x86_64.rpm 
-> The above warning has come up

**Comment by michaelklishin** [comment]
@hhhChan OK, perhaps I misread your post. You need to import the signing key first. There may be unresolved dependencies in the yum database.

The following succeeds for me using the `centos:7` Docker image:

```
yum update -y

rpm --import https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
curl -sLO https://github.com/rabbitmq/erlang-rpm/releases/download/v23.3.2/erlang-23.3.2-1.el7.x86_64.rpm
yum install ./erlang-23.3.2-1.el7.x86_64.rpm
```

The output to confirm:

```
Loaded plugins: fastestmirror, ovl
Examining ./erlang-23.3.2-1.el7.x86_64.rpm: erlang-23.3.2-1.el7.x86_64
Marking ./erlang-23.3.2-1.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package erlang.x86_64 0:23.3.2-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================================================================================================================
 Package                                                 Arch                                                    Version                                                         Repository                                                                    Size
====================================================================================================================================================================================================================================================================
Installing:
 erlang                                                  x86_64                                                  23.3.2-1.el7                                                    /erlang-23.3.2-1.el7.x86_64                                                   34 M

Transaction Summary
====================================================================================================================================================================================================================================================================
Install  1 Package

Total size: 34 M
Installed size: 34 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : erlang-23.3.2-1.el7.x86_64                                                                                                                                                                                                                       1/1
  Verifying  : erlang-23.3.2-1.el7.x86_64                                                                                                                                                                                                                       1/1

Installed:
  erlang.x86_64 0:23.3.2-1.el7

Complete!
```

**Comment by michaelklishin** [comment]
Perhaps removing the package with the unmet dependency as well as any existing `erlang` packages installed would help:

``` shell
yum remove -y erlang erlang-examples
```

Something like that.

I could not find `erlang-examples` in the standard Yum repositories, though.
