### ISSUE TITLE
eldap missing in package 

### ISSUE THREAD

**Issue by spham** [rabbitmq/erlang-rpm#95]
hi
i use rhel 7, 
- https://github.com/rabbitmq/erlang-rpm/releases/tag/v23.3.4.4
and source on 23.3.4.4  and get from packagecloud

and 
ls /usr/lib/rabbitmq/lib/rabbitmq_server-3.8.17/plugins | grep eldap return nothing

**Comment by michaelklishin** [comment]
`eldap` is a part of Erlang/OTP, it is not supposed to be under RabbitMQ installation's `plugins` directory.

**Comment by michaelklishin** [comment]
Whether `eldap` is present in an Erlang installation can be verified without involving RabbitMQ:

``` shell
erl

# and then run in the shell:
# application:ensure_all_started(eldap).
```

I'm trying to reproduce using `centos:7` from DockerHub.

**Comment by michaelklishin** [comment]
I cannot reproduce:

```
1> application:ensure_all_started(eldap).
{ok,[eldap]}
```

I used the Cloudsmith version of the instructions from this package's README.

My best guess is that your Erlang installation does not come from this package. See

``` bash
yum list erlang
```

to see what versions of the `erlang` package are available and from what repositories.

**Comment by spham** [comment]
i have this

```
yum list erlang
Modules complémentaires chargés : enabled_repos_upload, package_upload, product-id,
                                : search-disabled-repos, subscription-manager,
                                : tracer_upload
Paquets installés
erlang.x86_64                23.3.4.4-1.el7                 @/erlang-23.3.4.4-1.el7.x86_64
Uploading Enabled Repositories Report
2021-06-22 11:19:13,676 [WARNING] yum:18315:Dummy-1 @logutil.py:142 - logging already initialized
Cannot upload enabled repos report, is this client registered?
```

ans now 

```
[ansible@adrmq01d ~]$ erl
Erlang/OTP 23 [erts-11.2.2.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Eshell V11.2.2.3  (abort with ^G)
1> application:ensure_all_started(eldap)
1> 
```

i will try now with cloudsmith,

**Comment by michaelklishin** [comment]
I could not reproduce using PackageCloud either, which is not surprising given that only one package is produced and then published to both services.

**Comment by michaelklishin** [comment]
@spham you are missing the trailing dot after `application:ensure_all_started(eldap)`. It is mandatory as it completes the expression. In other words, you get no result because you haven't entered a complete expression.

I'm afraid I do not understand this part

> how on install erlang before rabbitmq-server, it will deploy on rabbitmq-server

RabbitMQ has a dedicated [Installation guide for RPM distributions](https://www.rabbitmq.com/install-rpm.html). CentOS 7
is no longer officially supported as it cannot run Erlang 24 with TLS 1.3 but CentOS 7 RPM packages are still produced for RabbitMQ 3.8 and Erlang 23. Nothing has changed in that are for either RabbitMQ or this package in a while.

**Comment by michaelklishin** [comment]
Here is what exactly you have to enter into the Erlang shell before hitting Enter:

```
application:ensure_all_started(eldap).
```

(note the trailing dot).

I'm afraid I don't have much time to spend on this. `eldap` is available in this package, as it should be.

**Comment by spham** [comment]
> @spham you are missing the trailing dot after `application:ensure_all_started(eldap)`. It is mandatory as it completes the expression. In other words, you get no result because you haven't entered a complete expression.
> 
> I'm afraid I do not understand this part
> 
> > how on install erlang before rabbitmq-server, it will deploy on rabbitmq-server
> 
> RabbitMQ has a dedicated [Installation guide for RPM distributions](https://www.rabbitmq.com/install-rpm.html). CentOS 7
> is no longer officially supported as it cannot run Erlang 24 with TLS 1.3 but CentOS 7 RPM packages are still produced for RabbitMQ 3.8 and Erlang 23. Nothing has changed in that are for either RabbitMQ or this package in a while.

yes,

i try now and it's ok

1> application:ensure_all_started(eldap).
{ok,[eldap]}

but whyt is ok
enable plugin is not possible ?

```
 sudo rabbitmq-plugins enable eldap
Enabling plugins on node rabbit@adrmq01d:
eldap
Error:
{:plugins_not_found, [:eldap]}
```

i use rhel7.9 and old erlang-23.3.4.4-1.el7.x86_64.rpm and rmq 3.8.17

**Comment by spham** [comment]
> Here is what exactly you have to enter into the Erlang shell before hitting Enter:
> 
> ```
> application:ensure_all_started(eldap).
> ```
> 
> (note the trailing dot).
> 
> I'm afraid I don't have much time to spend on this. `eldap` is available in this package, as it should be.

ok, it maybe available in erlang, but rabbitmq-server need this pagackage in /usr/lib/rabbitmq/lib/rabbitmq_server-3.8.17/plugins
