### ISSUE TITLE
Could you provide the 'erlang24' rpm package for CentOS7? thanks

### ISSUE THREAD

**Issue by tomyouyou** [rabbitmq/erlang-rpm#96]

**Comment by tomyouyou** [comment]
I found it in "https://packagecloud.io/rabbitmq/erlang"

**Comment by michaelklishin** [comment]
CentOS 7 does not provide OpenSSL 1.1 (it can be installed separately for CLI tools use but not as a system library), so no, we cannot produce a package for CentOS 7. Soon enough there will be no new releases of any of our packages for CentOS 7 as CentOS maintenance is moving to CentOS Stream exclusively starting in Jan 2022 IIRC>
