### ISSUE TITLE
that JIT has not been enabled for 'erlang-24.0.3-1.el8.x86_64.rpm'

### ISSUE THREAD

**Issue by tomyouyou** [rabbitmq/erlang-rpm#97]
I downloaded and installed the 'erlang-24.0.3-1.el8.x86_64.rpm' and found that JIT was disabled.
[root@ctrl1]# erl
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Eshell V12.0.3  (abort with ^G)
1>

**Comment by michaelklishin** [comment]
You haven't provided any evidence of that.

```
erlang:system_info(emu_flavor).
```

can be used as evidence.

The JIT is quietly excluded if the build environment is missing a C++17 compiler, so, `g++` must be [added to the build image](https://github.com/rabbitmq/erlang-rpm/blob/master/docker/Dockerfile.template).

**Comment by michaelklishin** [comment]
I have added `BuildDepends: clang` to `erlang.spec`. This will make sure that `gcc` and `gcc-c++` (the missing part) are also available.

Finally, the build env images were updated to install Clang/GCC with C++.

**Comment by michaelklishin** [comment]
For our Concourse env to be updated, we have to update another image. I'm on it.

**Comment by michaelklishin** [comment]
Done. From the most recent build:

```
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for C++17 support... yes
```

**Comment by michaelklishin** [comment]
I rebuilt the `24.0.3` release and republished it, including [to GitHub](https://github.com/rabbitmq/erlang-rpm/releases/tag/v24.0.3). There is no easy way to automatically bump the revision for this package and we don't know when a new patch release is going to come out, so I figured re-tagging and re-publishing would be the most pragmatic thing to do.
